### ISSUE TITLE
Tag missing

### ISSUE THREAD

**Issue by vpeter4** [notspiff/inputstream.rtmp#124]
Now that xbmc is at 21.0a1-Omega this addon could also be tagged?

**Comment by phunkyfish** [comment]
PR created: https://github.com/xbmc/inputstream.rtmp/pull/125

Windows builds are failing so need to wait to do the release.

**Comment by vpeter4** [comment]
Any news on this?

**Comment by phunkyfish** [comment]
I can’t get the build to complete, there is an issue with package downloads from mirrors for windows. Once I figure out what is going on there I can get this released.

**Comment by vpeter4** [comment]
I understand. And because of this pvr iptvsimple addon can't be installed :(

Why is this dependency even needed?

**Comment by phunkyfish** [comment]
And today magically it works. Release just finished building should start appearing on servers soon.

It's a dependency for supportability reasons.

It should happen in the future as add-on branching for binary-addons should include an initial build from V22.
