### ISSUE TITLE
create github tag

### ISSUE THREAD

**Issue by MartijnKaijser** [notspiff/inputstream.rtmp#13]
Any chance you could tag the new release (and all other add-ons you have) so i can use that reference for binary repo instead of a git SHA?

**Comment by akva2** [comment]
Not today. And i think i tagged this on last update

**Comment by MartijnKaijser** [comment]
nope ;)
tag is 1.0.2 and addon.xml says 1.0.3 

Didn't expect it to be done today either. Just something i wanted to get done before the binary addons rework starts to get merged

**Comment by akva2** [comment]
Ah right fernet did the last update:) then all is good. Only have my phone until tomorrow hence the response...

**Comment by akva2** [comment]
audiodecoder.2sf v1.1.0
audiodecoder.dumb v1.1.0
audecoder.fluidsynth v1.1.1
audiodecoder.gme v1.1.0
audiodecoder.gsf v1.1.0
audiodecoder.modplug v1.1.0
audiodecoder.ncsf v1.1.1
audiodecoder.nosefart v1.1.0
audiodecoder.openmpt v1.1.0
audiodecoder.organya v1.1.0
audiodecoder.qsf v1.1.0
audiodecoder.sidplay v1.1.0
audiodecoder.snesapu v1.1.0
audiodecoder.ssf v1.1.1
audiodecoder.stsound v1.1.0
audiodecoder.timidity v1.1.1
audiodecoder.vgmstream v1.1.0
inputstream.rtmp v1.0.3
screensaver.asteroids v1.1.2
screensaver.asterwave v1.1.0
screensaver.biogenesis v1.1.0
screensaver.cpblobs v1.1.0
screensaver.greynetic v1.1.0
screensaver.matrixtrails v1.1.0
screensaver.pingpong v1.1.0
screensaver.pyro v1.1.0
screensaver.stars v1.1.0
screensavers.rsxs v1.3.0
visualization.fishbmc v4.1.0
visualization.goom v1.1.0
visualization.projectm v1.1.1
visualization.shadertoy v1.1.5
visualization.spectrum v1.1.1
visualization.waveform v1.1.0

**Comment by MartijnKaijser** [comment]
thx much
