### ISSUE TITLE
latest Krypton nightlies for WIN32 - failed to load error

### ISSUE THREAD

**Issue by mgonzales71** [notspiff/inputstream.rtmp#16]
`ERROR: Win32DllLoader::Load: Failed to load "C:\Program Files (x86)\Kodi\addons\inputstream.rtmp\inputstream.rtmp.dll" with error 126: "The specified module could not be found."
`

strange thing is if I open the Addons DB and remove it's entry from the table "installed" and then enable it via the GUI it works until I quit and re-start Kodi giving the error above.

actually maybe I should also try to disable it, restart and enable it to see if I get the same behavior...

let me do that and update this with the results here in a few mins..

**Comment by mgonzales71** [comment]
ok - just quick update - the 5th restart of Kodi I now get same error noted above.

Note: it was after a crash of Kodi and restart that also coincided with the failure to load.  they could be totally unrelated since I don't have a good enough log of any cause and effect yet.

maybe if I knew what typical things could cause the error 126 module not found for an addon

**Comment by mgonzales71** [comment]
still happens - have tried clean installs etc

point me in a direction at least?

**Comment by malvinas2** [comment]
Mario, did you find the cause for this error message? 
I've found the same error in my kodi-log, but nevertheless video-addons using the inputstream seem to work well (?).

**Comment by mgonzales71** [comment]
No I did not - I did however notice that when I switched to using the Kodi 18 / Leia nightlies that I no longer saw this error.

Wish I could offer more insight I tried forums / bug report / here and not one person ever offered any insight etc 

Glad you aren’t seeing any issues it was so frustrating that I just decided to just use and deal with the other side of coin and the headaches that come with alpha software

**Comment by notspiff** [comment]
The addon api has changed, master is only compatible with 18, use the tagged version for 17, ref kodi-binary-addons repo
