### ISSUE TITLE
Problems with handling of "session"

### ISSUE THREAD

**Issue by mwelinder** [notspiff/inputstream.rtmp#17]
1. If Open fails, session will be left non-null
2. Nothing appears to call RTMP_free

**Comment by notspiff** [comment]
1. I have added nulling of the ptr in https://github.com/notspiff/inputstream.rtmp/commit/6c1af46a59f59d8fe22f772ac53eee30968e242a
2. It should be free'd, ref https://github.com/notspiff/inputstream.rtmp/blob/master/src/RTMPStream.cpp#L144

**Comment by mwelinder** [comment]
Thanks.

Re 2: you are referencing an RTMP_Close() call.  That only closes the stream and frees some memory that was allocated as part of the RTMP_Connect and other calls.

Memory that was allocated with RTMP_Alloc() still needs to be freed with a call to RTMP_Free.

https://github.com/jaehyunp/rtmpdump/blob/master/librtmp/rtmp.c#L320
(not an official repository -- just what google gave me)

**Comment by notspiff** [comment]
right you are. funny, kodi has been doing this wrong for many years as i
just copied the code from core. will fix, thanks.

**Comment by notspiff** [comment]
finally done. thx
