### ISSUE TITLE
imports kodi.inputstream 1.0.0 (Kodi 17 master provides only 1.0.5)

### ISSUE THREAD

**Issue by MilhouseVH** [notspiff/inputstream.rtmp#2]
https://github.com/notspiff/inputstream.rtmp/blob/master/inputstream.rtmp/addon.xml.in#L8
```
 <import addon="kodi.inputstream" version="1.0.0"/>
```
Does this need to be bumped to 1.0.5?

I'm not entirely sure how to read the `kodi.inputstream` addon.xml:

https://github.com/xbmc/xbmc/blob/master/addons/kodi.inputstream/addon.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<addon id="kodi.inputstream" version="1.0.5" provider-name="Team Kodi">
  <backwards-compatibility abi="1.0.5"/>
  <requires>
    <import addon="xbmc.core" version="0.1.0"/>
  </requires>
</addon>
```

It specifies `<backwards-compatibility abi="1.0.5"/>` which I'm assuming means that any add-on that requires an earlier version (such as 1.0.0) is now incompatible.

We're having trouble installing `inputstream.rtmp` with LibreELEC 7.90.004 which ships with Kodi 17 Alpha3 and `kodi.inputstream` 1.0.4 - we get the following error from the addons system:
```
20:56:54 726.564087 T:1962143744   ERROR: ADDON: no available versions of inputstream.rtmp
```

**Comment by akva2** [comment]
you read it correctly. it has been bumped in master. i could load the addon again, but i had no working rtmp stream at hand to test as such.

**Comment by MilhouseVH** [comment]
Many thanks, I'll close this issue.
