### ISSUE TITLE
API change

### ISSUE THREAD

**Issue by peak3d** [notspiff/inputstream.rtmp#26]
https://github.com/notspiff/inputstream.rtmp/blob/master/src/RTMPStream.cpp#L107

its now bool return value, pls. simply return false.
false means: no demux reset.

**Comment by notspiff** [comment]
now as in live in master? thanks for heads-up!

**Comment by notspiff** [comment]
i see it is. https://github.com/notspiff/inputstream.rtmp/commit/e094fa3868a6a77a15a50b6c3873c64620922328
