### ISSUE TITLE
Include all ffmpeg parameters ?

### ISSUE THREAD

**Issue by hdgdl** [notspiff/inputstream.rtmp#5]
As far as i can tell not all parameters available in ffmpeg/rtmpdump are included.
Will the missing ones, like app or conn (For amf stuff) or token be added later on ?

Reference: https://rtmpdump.mplayerhq.hu/rtmpdump.1.html

The current windows ffmpeg implementation in kodi is missing parameters too
https://github.com/xbmc/xbmc/pull/10015

Thanks in advance

**Comment by notspiff** [comment]
i ported the existing code. patches welcome for anything missing, i have no
way to test so better somebody who do adds it.

18. sep. 2016 11.55 p.m. skrev "hdgdl" <notifications@github.com>:

**Comment by notspiff** [comment]
also do note that the list given in the code is there for legacy reasons.
you should be allowed to pass all options supported by librtmp in the
format expected by librtmp (evil space separated name=val after the actual
url).

18. sep. 2016 11.58 p.m. skrev "Arne Morten Kvarving" <cptspiff@gmail.com>:

**Comment by hdgdl** [comment]
Thanks for the reply

On windows it wont recognize app or conn
Additionaly if the rtmp url looks like "rtmp://blabla:1935/Path/Blabla" kodi requests only "/path" for app not "/Path/Blabla"

Will test again with linux/libreelec an report back

**Comment by worstperson** [comment]
From an initial look, the problem might be that RTMP_SetOpt() only gets called for options that exist in the options list. Will have a closer look when I get off of work.

**Comment by worstperson** [comment]
I know it's a bit late, but it ended up being my setup that was wrong not the inputstream code. My use case  only uses multiple 'conn' parameters, I did not test for the 'app' issue mentioned by hdgdl.

**Comment by notspiff** [comment]
Aight.
