### ISSUE TITLE
[Raspberry Pi OS (Bullseye)] arm | Kodi missing inputstream.rtmp

### ISSUE THREAD

**Issue by ReWiG** [notspiff/inputstream.rtmp#90]
Is there any inputstream.ffmpegdirect addon for Linux version?
I am using a freshly installed version of Kodi 19.3 from the official Raspberry Pi OS Bullseye repository. In the app store, I just don't have the inputstream.rtmp extension, although it is a dependency for the InputStream Adaptive and without it, I keep getting an error when starting the broadcast.
`uname -a Linux kodi 5.10.83-v7l+ #1499 SMP Tue Dec 7 14:08:09 GMT 2021 armv7l GNU/Linux `

**Comment by phunkyfish** [comment]
I’ll close this duplicate issue. RTMP is unrelated.
